services:
  frontend-dev:
    image: node:20-alpine
    container_name: email_analyzer_frontend_dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8088:8080"
    command: sh -c "npm install && npm run serve"
    environment:
      - VUE_APP_API_URL=http://localhost:8000/api

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_analyzer_frontend
    restart: always
    ports:
      - "8088:80"
    environment:
      - VUE_APP_API_URL=http://localhost:8000/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 