services:
  api:
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - ENV=dev
      - DEBUG=True
    volumes:
      - ./app:/app  # Mount code để hot reload 