services:
  api:
    build: .
    container_name: email_analyzer_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  app_data: 